
version: '3'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ./backend:/app
    restart: unless-stopped
  
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    depends_on:
      - backend
